/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 22
#define YY_END_OF_BUFFER 23
static yyconst short int yy_accept[236] =
    {   0,
        0,    0,   23,   21,    3,   20,   17,   21,   17,   17,
       17,   21,   17,   17,   17,   17,   17,   17,   17,    9,
        8,   17,   17,   17,   17,   18,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   17,   17,   17,    0,   19,    0,   17,    0,
        0,   17,    0,    0,   17,    0,   11,    0,    6,   11,
        9,    0,    0,    9,    9,    0,    8,    8,    8,   17,
       17,   18,   18,   18,   18,   18,   18,   18,    4,   18,
       18,   18,   18,   18,   18,    4,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,    0,    0,

       13,    0,    0,    0,    0,   11,   11,    0,    0,    6,
        0,   12,    9,    9,   10,    8,    8,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,    0,    0,   14,   15,    0,    0,
        0,   11,   11,   11,    7,   12,   12,   10,   10,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,    0,
        0,    0,   16,    0,   12,   12,   10,   10,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,

       18,   18,    0,    0,   18,   18,   18,    5,   18,   18,
       18,    0,    0,   18,   18,   18,   18,    0,    0,    2,
        0,    0,    0,    2,    0,    2,    0,    1,    0,    2,
        0,    2,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   31,
       31,   31,   31,   31,   33,   31,   31,   34,   31,   31,
       35,   36,   37,   38,   31,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   31,   48,   49,   50,   51,
       52,   53,   31,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[67] =
    {   0,
        1,    1,    2,    3,    1,    4,    1,    1,    1,    5,
        6,    7,    8,    1,    9,    1,    1,   10,   11,   11,
       12,    8,    1,    8,    1,   13,   14,   15,   15,   15,
       16,   16,   16,   16,    1,   17,    1,    1,   18,   18,
       15,   15,   15,   18,   16,   16,   16,   16,   16,   16,
       19,   16,   16,   19,   16,   19,   16,   19,   16,   19,
       16,   16,    1,    8,    1,    1
    } ;

static yyconst short int yy_base[252] =
    {   0,
        0,    0,  551,  552,  552,  552,  525,   61,   61,  524,
       60,  512,  552,  522,   56,  552,   57,   55,   66,   92,
      136,   53,  521,   61,  552,    0,  520,  487,  489,   49,
       28,   45,   40,  490,   49,  489,  497,   60,  478,  487,
      485,  490,   65,  552,  552,   92,  552,   96,  552,  492,
      483,  552,  523,   98,  552,  515,  118,  518,    0,  151,
       70,  167,  183,   66,   78,    0,    0,   87,   82,  505,
      504,    0,  472,  484,  471,  486,  473,  479,  465,  466,
      463,  463,  466,  463,  460,    0,  459,  463,   77,  461,
       89,  106,  465,  458,   99,   93,  463,  130,  463,  463,

      552,  493,  154,    0,  192,  127,  133,  487,  480,    0,
      170,  195,  552,  552,  185,  552,  552,  442,  450,  431,
      416,  164,  428,  423,  418,  407,  412,  412,  396,  402,
      397,  385,  382,  381,  386,  372,  368,  368,  380,  370,
      373,  377,  376,  363,  364,  361,  552,  552,  211,  399,
      203,  216,  552,  552,  552,  143,  196,  172,  196,  360,
      351,  359,  348,  355,  349,  346,  344,  344,  340,  352,
      340,  344,  349,  348,  346,  334,  339,  326,  338,  326,
      319,  364,  552,  363,  552,  552,  552,  552,  302,  293,
      296,  287,  273,  277,  284,  281,  282,  266,  275,  277,

      268,  267,  268,  268,  236,  212,  224,    0,  222,  221,
      214,  258,  216,  215,  202,  211,  195,  229,  237,  243,
      245,  226,  183,  203,    0,  246,  176,  552,  152,  139,
      186,  111,    0,  240,  552,  269,  288,  297,  313,  332,
      351,  360,  368,  382,  398,  415,  434,  453,  472,  477,
      490
    } ;

static yyconst short int yy_def[252] =
    {   0,
      235,    1,  235,  235,  235,  235,  235,  236,  235,  235,
      235,  237,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  238,  235,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  235,  235,  235,  236,  235,  236,  235,  235,
      235,  235,  235,  239,  235,  235,  235,  240,  241,  235,
       20,  235,  235,  235,  235,  242,   21,  235,  235,  235,
      235,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  236,  235,  235,

      235,  235,  235,  243,  235,  235,  235,  240,  235,  241,
      235,  235,  235,  235,  242,  235,  235,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  235,  235,  235,  235,  235,  244,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,

      238,  238,  235,  235,  238,  238,  238,  238,  238,  238,
      238,  235,  235,  238,  238,  238,  238,  245,  235,  246,
      235,  247,  248,  249,  250,  246,  247,  235,  248,  249,
      251,  235,  250,  251,    0,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235
    } ;

static yyconst short int yy_nxt[619] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   16,   16,   22,   23,   24,   25,   26,   26,   26,
       26,   26,   26,   26,   13,    4,   13,   27,   28,   29,
       30,   31,   32,   33,   34,   26,   35,   26,   36,   26,
       26,   26,   26,   37,   38,   39,   40,   41,   42,   26,
       26,   26,   13,   43,   13,   44,   47,   49,   45,   55,
       78,   56,   55,   57,   57,   57,   70,   45,   58,   79,
       52,   52,   55,   59,   52,   45,   71,   75,   83,   52,
       45,   84,   86,   80,   76,   81,   48,   47,  113,   87,

       77,   98,   50,  235,   82,   90,   91,   51,   60,  114,
       61,   61,   62,  117,  224,   92,  103,  103,   93,  116,
       63,  131,  113,   64,   65,   66,  114,   48,   45,  235,
      117,   48,  132,  134,   63,   47,   57,   57,   57,  142,
       64,  143,  235,  116,  136,  140,  105,  106,   65,  107,
      135,   66,   60,  141,   67,   67,   67,  104,  153,  137,
      105,  106,  154,  148,   63,   48,  107,   68,   69,   57,
       57,   57,  149,  149,  185,  153,  154,  228,   63,  105,
      106,  228,  107,   60,   68,   62,   62,   62,  112,  112,
      112,  185,   69,  105,  106,   63,  111,  232,  111,  107,

      233,  112,  112,  112,  187,  151,  224,  151,  228,   63,
      152,  152,  152,  112,  112,  112,  158,  159,  161,  162,
      148,  152,  152,  152,  156,  186,  157,  188,  187,  182,
      182,  228,  218,  158,  152,  152,  152,   86,  156,  186,
      221,  159,  222,  157,  188,  106,  224,  107,  221,  224,
      222,  232,   86,  225,  233,   86,  225,   86,  219,  106,
      223,  218,  217,  216,  107,   86,  215,   86,  223,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   53,   53,
       53,   53,  214,   53,   53,   53,   53,   53,   53,   53,

       53,   53,   53,   53,   53,   53,   53,   72,   72,  213,
      212,   72,   72,  211,   72,   72,  102,  102,  210,  209,
       86,   86,   86,  102,  208,   86,  102,   86,  207,  102,
      102,  102,  108,  108,  108,  108,  108,   86,   86,  108,
      108,  206,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  110,  205,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      115,  115,  183,  148,  115,  204,  203,  115,  150,  150,
       86,  202,  150,  201,   86,  150,  184,  200,  199,  198,
      197,  196,  184,  184,  195,   86,  184,  194,  193,  184,

      220,   86,  192,  191,  190,  189,   86,   86,  183,  181,
      180,  179,  220,  220,  178,  220,  220,  226,   86,  177,
      226,  176,  175,  174,  173,  226,  226,  172,  171,  226,
      226,  170,  226,  226,  227,  169,  227,  227,  227,  227,
      227,  168,  227,  167,  227,  227,   86,   86,  227,  227,
      166,  227,  227,  229,  165,  229,   86,  229,  229,  229,
       86,  229,  164,  229,  229,  229,  163,  229,  229,   86,
      229,  229,  230,   86,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  160,  230,
      230,  231,  231,   86,  231,  231,  234,  155,  234,  109,

      234,  234,  147,  146,  234,  234,  145,  234,  234,  144,
      139,  138,  133,  130,   86,  129,   86,  128,  127,  126,
      125,  124,  123,  122,  121,  120,  119,  118,   52,   52,
      109,   49,  101,  100,   99,   97,   96,   95,   94,   89,
       88,   85,   74,   73,   52,   45,   45,   54,   52,   45,
      235,    3,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,

      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235
    } ;

static yyconst short int yy_chk[619] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,    9,   11,   15,
       31,   18,   17,   18,   18,   18,   22,   22,   19,   31,
       15,   17,   17,   19,   11,   24,   24,   30,   33,   43,
       19,   33,   35,   32,   30,   32,    8,   46,   64,   35,

       30,   48,    9,   61,   32,   38,   38,    9,   20,   65,
       20,   20,   20,   69,  232,   38,   54,   54,   38,   68,
       20,   89,   64,   20,   20,   20,   65,   46,   43,   61,
       69,   48,   89,   91,   20,   98,   57,   57,   57,   96,
       20,   96,  230,   68,   92,   95,   57,   57,   20,   57,
       91,   20,   21,   95,   21,   21,   21,   54,  106,   92,
       57,   57,  107,  103,   21,   98,   57,   21,   21,   60,
       60,   60,  103,  103,  156,  106,  107,  229,   21,   60,
       60,  227,   60,   62,   21,   62,   62,   62,  111,  111,
      111,  156,   21,   60,   60,   62,   63,  231,   63,   60,

      231,   63,   63,   63,  158,  105,  224,  105,  223,   62,
      105,  105,  105,  112,  112,  112,  115,  115,  122,  122,
      149,  151,  151,  151,  112,  157,  112,  159,  158,  149,
      149,  222,  218,  115,  152,  152,  152,  217,  112,  157,
      219,  115,  219,  112,  159,  152,  220,  152,  221,  226,
      221,  234,  216,  220,  234,  215,  226,  214,  213,  152,
      219,  212,  211,  210,  152,  209,  207,  206,  221,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  237,  237,
      237,  237,  205,  237,  237,  237,  237,  237,  237,  237,

      237,  237,  237,  237,  237,  237,  237,  238,  238,  204,
      203,  238,  238,  202,  238,  238,  239,  239,  201,  200,
      199,  198,  197,  239,  196,  195,  239,  194,  193,  239,
      239,  239,  240,  240,  240,  240,  240,  192,  191,  240,
      240,  190,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  241,  189,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      242,  242,  184,  182,  242,  181,  180,  242,  243,  243,
      179,  178,  243,  177,  176,  243,  244,  175,  174,  173,
      172,  171,  244,  244,  170,  169,  244,  168,  167,  244,

      245,  166,  165,  164,  163,  162,  161,  160,  150,  146,
      145,  144,  245,  245,  143,  245,  245,  246,  142,  141,
      246,  140,  139,  138,  137,  246,  246,  136,  135,  246,
      246,  134,  246,  246,  247,  133,  247,  247,  247,  247,
      247,  132,  247,  131,  247,  247,  130,  129,  247,  247,
      128,  247,  247,  248,  127,  248,  126,  248,  248,  248,
      125,  248,  124,  248,  248,  248,  123,  248,  248,  121,
      248,  248,  249,  120,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  119,  249,
      249,  250,  250,  118,  250,  250,  251,  109,  251,  108,

      251,  251,  102,  100,  251,  251,   99,  251,  251,   97,
       94,   93,   90,   88,   87,   85,   84,   83,   82,   81,
       80,   79,   78,   77,   76,   75,   74,   73,   71,   70,
       58,   56,   53,   51,   50,   42,   41,   40,   39,   37,
       36,   34,   29,   28,   27,   23,   14,   12,   10,    7,
        3,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,

      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "TP3.l"
#define INITIAL 0
#line 4 "TP3.l"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <conio.h>
#include <math.h>
#include <string.h>
#include "superfunciones.c"

Node* listaCadenas=NULL;
Node* listaId=NULL;
Node2* listaPalRes=NULL;
Node* listaHexa=NULL;
Node* listaOctal=NULL;
Node2* listaDec=NULL;
Node2* listaReal=NULL;
Node2* listaCar=NULL;
Node* listaOp=NULL;
Node3* listaComent=NULL;
int linea = 1;
Node* listaNoRec=NULL;

#line 607 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 52 "TP3.l"


#line 761 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 236 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 552 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 54 "TP3.l"
{;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 55 "TP3.l"
{;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 56 "TP3.l"
{;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 57 "TP3.l"
{char* nuevoPalRes = (char*)malloc(yyleng+1);
                       strcpy(nuevoPalRes, yytext);
                       listaPalRes = agregarPalRes(nuevoPalRes, listaPalRes);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 60 "TP3.l"
{char* nuevoSizeOf = (char*)malloc(yyleng+1);
          strcpy(nuevoSizeOf, yytext);
          listaPalRes = agregarPalRes(nuevoSizeOf, listaPalRes);
          listaOp = agregarId(nuevoSizeOf, listaOp);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 64 "TP3.l"
{char* nuevoComentario = (char*)malloc(yyleng+1);
                         strcpy(nuevoComentario, yytext);
                         listaComent = agregarAListaComentarios(nuevoComentario, 0, listaComent);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "TP3.l"
{char* nuevoComentario = (char*)malloc(yyleng+1);
                          strcpy(nuevoComentario, yytext);
                          listaComent = agregarAListaComentarios(nuevoComentario, 1, listaComent);
                          linea += lineasComentariosMultilinea(nuevoComentario, yyleng);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 71 "TP3.l"
{char* nuevoDec = (char*)malloc(yyleng+1);
                                  strcpy(nuevoDec, yytext);
                                  listaDec = agregarConstanteDec(nuevoDec, listaDec);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 74 "TP3.l"
{char* nuevoOctal = (char*)malloc(yyleng+1);
                             strcpy(nuevoOctal, yytext);
                             listaOctal = agregarConstante(nuevoOctal, yyleng, listaOctal);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 77 "TP3.l"
{char* nuevoHexa = (char*)malloc(yyleng+1);
                                      strcpy(nuevoHexa, yytext);
                                      listaHexa = agregarConstante(nuevoHexa, yyleng, listaHexa);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 80 "TP3.l"
{char* nuevoReal = (char*)malloc(yyleng+1);
                                                   strcpy(nuevoReal, yytext);
                                                   listaReal = agregarConstanteDec(nuevoReal, listaReal);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 83 "TP3.l"
{char* nuevoReal = (char*)malloc(yyleng+1);
                                        strcpy(nuevoReal, yytext);
                                        listaReal = agregarConstanteDec(nuevoReal, listaReal);;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 86 "TP3.l"
{char* nuevoCar = (char*)malloc(yyleng+1);
                      strcpy(nuevoCar, yytext);
                      listaCar = agregarPalRes(nuevoCar, listaCar);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 89 "TP3.l"
{char* nuevoCar = (char*)malloc(yyleng+1);
                           strcpy(nuevoCar, yytext);
                           listaCar = agregarPalRes(nuevoCar, listaCar);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 92 "TP3.l"
{char* nuevoCar = (char*)malloc(yyleng+1);
                          strcpy(nuevoCar, yytext);
                          listaCar = agregarPalRes(nuevoCar, listaCar);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 95 "TP3.l"
{char* nuevoCar = (char*)malloc(yyleng+1);
                                strcpy(nuevoCar, yytext);
                                listaCar = agregarPalRes(nuevoCar, listaCar);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 98 "TP3.l"
{char* nuevoOp = (char*)malloc(yyleng+1);
                                                                       strcpy(nuevoOp, yytext);
                                                                       listaOp = agregarId(nuevoOp, listaOp);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 101 "TP3.l"
{char* nuevoId = (char*)malloc(yyleng+1);
                  strcpy(nuevoId, yytext);
                  listaId = agregarId(nuevoId, listaId);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 104 "TP3.l"
{char* nuevoLitCadena = (char*)malloc(yyleng+1);
                  strcpy(nuevoLitCadena, yytext);
                  listaCadenas = agregarCadena(nuevoLitCadena, (yyleng - 2), listaCadenas);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 107 "TP3.l"
{linea++;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 108 "TP3.l"
{char* nuevoNoRec = (char*)malloc(yyleng+1);
   strcpy(nuevoNoRec, yytext);
   listaNoRec = agregarCadena(nuevoNoRec, linea, listaNoRec);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 112 "TP3.l"
ECHO;
	YY_BREAK
#line 990 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 236 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 236 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 235);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 112 "TP3.l"




int main() {

    FILE* f = fopen("reporte.txt", "w+t");

    yyin = fopen("entrada.c", "r+t");

    yylex();

    printf(" -------------------------------------------\n -------------- R E P O R T E --------------\n -------------------------------------------\n");
    fprintf(f," -------------------------------------------\n -------------- R E P O R T E --------------\n -------------------------------------------\n");
    printf(" LISTA DE IDENTIFICADORES:------------------\n .\n .\tID\t\tAPARICIONES\n .\n");
    fprintf(f," LISTA DE IDENTIFICADORES:------------------\n .\n .\tID\t\tAPARICIONES\n .\n");
    imprimirId(listaId,f);
    printf(" .\n");
    fprintf(f," .\n");
    
    printf(" LISTA DE LITERALES CADENA:-----------------\n .\n .\tCADENA\t\t\t\tLONGITUD\n .\n");
    fprintf(f," LISTA DE LITERALES CADENA:-----------------\n .\n .\tCADENA\t\t\t\tLONGITUD\n .\n");
    imprimirCadenas(listaCadenas,f);
    printf(" .\n");
    fprintf(f," .\n");

    printf(" LISTA DE PALABRAS RESERVADAS:--------------\n .\n .\tPALABRA\n .\n");
    fprintf(f," LISTA DE PALABRAS RESERVADAS:--------------\n .\n .\tPALABRA\n .\n");
    imprimirPalRes(listaPalRes,f);
    printf(" .\n");
    fprintf(f," .\n");

    printf(" LISTA DE CONSTANTES HEXA:------------------\n .\n .\tVALOR HEXA\tVALOR DECIMAL\n .\n");
    fprintf(f," LISTA DE CONSTANTES HEXA:------------------\n .\n .\tVALOR HEXA\tVALOR DECIMAL\n .\n");
    imprimirHexa(listaHexa,f);
    printf(" .\n");
    fprintf(f," .\n");

    printf(" LISTA DE CONSTANTES OCTAL:-----------------\n .\n .\tVALOR OCTAL\tVALOR DECIMAL\n .\n");
    fprintf(f," LISTA DE CONSTANTES OCTAL:-----------------\n .\n .\tVALOR OCTAL\tVALOR DECIMAL\n .\n");
    imprimirOctal(listaOctal,f);
    printf(" .\n");
    fprintf(f," .\n");

    printf(" LISTA DE CONSTANTES DECIMAL:---------------\n .\n .\tVALOR DECIMAL\n .\n");
    fprintf(f," LISTA DE CONSTANTES DECIMAL:---------------\n .\n .\tVALOR DECIMAL\n .\n");
    int totalDecimal = imprimirDec(listaDec,f);
    printf(" .\n .\tTOTAL ACUMULADO DE CONSTANTES DECIMALES:  %d\n", totalDecimal);
    fprintf(f," .\n .\tTOTAL ACUMULADO DE CONSTANTES DECIMALES:  %d\n", totalDecimal);
    printf(" .\n");
    fprintf(f," .\n");

    printf(" LISTA DE CONSTANTES REALES:----------------\n .\n .\tPARTE ENTERA\t\tPARTE FRACCIONAL\n .\n");
    fprintf(f," LISTA DE CONSTANTES REALES:----------------\n .\n .\tPARTE ENTERA\t\tPARTE FRACCIONAL\n .\n");
    imprimirReal(listaReal,f);
    printf(" .\n");
    fprintf(f," .\n");

    printf(" LISTA DE CONSTANTES CARACTER:--------------\n .\n .\tCARACTER\n .\n");
    fprintf(f," LISTA DE CONSTANTES CARACTER:--------------\n .\n .\tCARACTER\n .\n");
    imprimirPalRes(listaCar,f);
    printf(" .\n");
    fprintf(f," .\n");

    printf(" LISTA DE C.P y OPERADORES:-----------------\n .\n .\tCARACTER\tAPARICIONES\n .\n");
    fprintf(f," LISTA DE C.P y OPERADORES:-----------------\n .\n .\tCARACTER\tAPARICIONES\n .\n");
    imprimirId(listaOp,f);
    printf(" .\n");
    fprintf(f," .\n");
    
    printf(" LISTA DE COMENTARIOS:-----------------------\n .\n .\tTIPO\t\tCOMENTARIO\n .\n");
    fprintf(f," LISTA DE COMENTARIOS:-----------------------\n .\n .\tTIPO\t\t\t\tCOMENTARIO\n .\n");
    imprimirComentarios(listaComent, f);
    printf(" .\n");
    fprintf(f," .\n");

    printf(" LISTA DE CARACTERES NO RECONOCIDOS:--------\n .\n .\tCARACTER\tLINEA\n .\n");
    fprintf(f," LISTA DE CARACTERES NO RECONOCIDOS:--------\n .\n .\tCARACTER\tLINEA\n .\n");
    imprimirCadenas(listaNoRec,f);
    printf(" .\n");
    fprintf(f," .\n");
    
    fclose(f);
    return 0;
}
